import Footer from "@/components/footer";
import Header from "@/components/header";
import { Box } from "@chakra-ui/react";
import Head from "next/head";

export default function Layout({ children, metaTitle, metaDescription }) {
  return (
    <div>
      <Head>
        <title>{`Next Mini Project ${metaTitle}`}</title>
        <meta
          name="description"
          content={metaDescription || "Generated by Next Mini Project"}
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Box flex="1">
        <Box minH={{ base: "100vh", md: "calc(100vh - 80px)" }}>{children}</Box>
      </Box>
      <Footer />
    </div>
  );
}
